<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        @page {
            size: A4;
            margin: 25mm;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            position: relative;
        }

        .title {
            text-align: center;
            font-size: 20pt;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .box {
            border: 1px solid #222;
            padding: 20px;
        }

        .mt {
            margin-top: 16px;
        }

        .sig {
            margin-top: 60px;
            display: flex;
            justify-content: space-between;
        }

        .sig .line {
            border-top: 1px solid #333;
            width: 260px;
            text-align: center;
            padding-top: 6px;
        }

        p {
            font-size: 12pt;
            line-height: 1.5;
        }

        /* ✅ Watermark Logo CSS */
        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            opacity: 0.08;
            /* make it light */
            z-index: -1;
            /* put behind text */
            pointer-events: none;
        }

        .watermark img {
            width: 500px;
            /* adjust size */
        }
    </style>
</head>

<body>
    <!-- Watermark Logo -->
    <div class="watermark">
        <img src="{{ public_path('images/logo.png') }}" alt="Watermark Logo">
    </div>

    <div class="title">CERTIFICATE OF ELIGIBILITY TO DEFEND</div>

    <div class="box">
        <p>This is to certify that <strong>{{ $student->name }}</strong> ({{ $thesis->course->name }})
            has complied with the e-thesis submission requirements (complete manuscript and endorsement letter) for the
            thesis entitled:</p>

        <p class="mt" style="font-style:italic; font-weight:bold;">“{{ $thesis->title }}”</p>

        @if ($thesis->adviser)
            <p class="mt">Adviser: <strong>{{ $thesis->adviser }}</strong></p>
        @endif

        <p class="mt">Accordingly, the student is <strong>ELIGIBLE TO DEFEND</strong> as of {{ $approvedAt }}.</p>
    </div>

    <div class="sig">
        {{-- <div class="line">{{ $controller }}</div> --}}
        <div class="line">Dean / Program Chair</div>
    </div>

    <p class="mt" style="font-size:10pt;">Generated by the e-Thesis System on {{ now()->format('F d, Y h:i A') }}
    </p>
</body>

</html>
