<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <style>
        @page {
            size: A4;
            margin: 25mm;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            position: relative;
        }

        .title {
            text-align: center;
            font-size: 20pt;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .box {
            border: 1px solid #222;
            padding: 20px;
        }

        .mt {
            margin-top: 16px;
        }

        .sig {
            margin-top: 60px;
            display: flex;
            justify-content: space-between;
        }

        .sig .line {
            border-top: 1px solid #333;
            width: 260px;
            text-align: center;
            padding-top: 6px;
        }

        p {
            font-size: 12pt;
            line-height: 1.5;
        }

        /* ✅ Watermark Logo CSS */
        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            opacity: 0.08;
            /* make it light */
            z-index: -1;
            /* put behind text */
            pointer-events: none;
        }

        .watermark img {
            width: 500px;
            /* adjust size */
        }

        .qr {
            position: absolute;
            /* was fixed */
            right: 0mm;
            bottom: 0mm;
            text-align: center;
            font-size: 9pt;
            color: #333;
        }

        .qr .code {
            margin-bottom: 6px;
        }
    </style>
</head>

<body>
    <!-- Watermark Logo -->
    <div class="watermark">
        <img src="{{ public_path('images/logo.png') }}" alt="Watermark Logo">
    </div>

    @php($adviserName = optional($thesis->thesisTitle->adviserUser)->name)

    <div class="title">{{ $stageLabel ?? 'CERTIFICATE OF ELIGIBILITY TO DEFEND' }}</div>
    <p class="mt" style="font-size:10pt;">
        Verification code: <strong>{{ strtoupper($visibleCode) }}</strong>
    </p>
    <div class="box">
        <p>This is to certify that <strong>{{ $student->name }}</strong> ({{ optional($thesis->thesisTitle->course)->name }})
            has complied with the e-thesis submission requirements (complete manuscript and endorsement letter) for the
            thesis entitled:</p>

        <p class="mt" style="font-style:italic; font-weight:bold;">“{{ $thesis->thesisTitle->title }}”</p>

        @if ($adviserName)
            <p class="mt">Adviser: <strong>{{ $adviserName }}</strong></p>
        @endif

        @if ($thesis->thesisTitle->panel_chairman || $thesis->thesisTitle->panelist_one || $thesis->thesisTitle->panelist_two)
            <p class="mt"><strong>Panel Members</strong></p>
            @if ($thesis->thesisTitle->panel_chairman)
                <p>Chairman: <strong>{{ $thesis->thesisTitle->panel_chairman }}</strong></p>
            @endif
            @if ($thesis->thesisTitle->panelist_one)
                <p>Panelist 1: <strong>{{ $thesis->thesisTitle->panelist_one }}</strong></p>
            @endif
            @if ($thesis->thesisTitle->panelist_two)
                <p>Panelist 2: <strong>{{ $thesis->thesisTitle->panelist_two }}</strong></p>
            @endif
        @endif

        @if ($thesis->thesisTitle->defense_date)
            <p class="mt">Scheduled Defense: <strong>{{ $thesis->thesisTitle->defense_date->format('F d, Y') }}</strong></p>
        @endif

        <p class="mt">Accordingly, the student is <strong>ELIGIBLE TO DEFEND {{ strtoupper($stageName ?? 'Final Defense') }}</strong> as of {{ $approvedAt }}.</p>
    </div>

    <div class="sig">
        {{-- <div class="line">{{ $controller }}</div> --}}
        <div class="line">Dean / Program Chair</div>
    </div>

    <p class="mt" style="font-size:10pt;">Generated by the e-Thesis System on {{ now()->format('F d, Y h:i A') }}
    </p>

    {{-- ✅ QR Code block --}}
    <div class="qr">
        <div class="code">
            <img src="data:image/png;base64,{{ $qrPng }}" alt="QR Code" width="110" height="110">
        </div>
        <div>Scan to verify</div>
        {{-- <div style="word-break: break-all;">{{ $verifyUrl }}</div> --}}
    </div>

</body>

</html>
